# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [253]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [254]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3/envs/numpyPrjct\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS',

#### 3. Create a null vector of size 10 (★☆☆)

In [255]:
nullVec = np.zeros(10)
nullVec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [256]:
#help(np.ndarray)
nullVec.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [257]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [258]:
nullVec = np.zeros(10, dtype=np.int64)
nullVec[4] = 1
nullVec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [259]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [260]:
reversed = np.flip(vector)
reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [261]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [262]:
array = np.array([1,2,0,0,4,0])
array.nonzero()[0]

array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [263]:
idMat = np.eye(3)
idMat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [264]:
rng = np.random.default_rng()
tensor = rng.random((3,3,3))
tensor

array([[[7.93732319e-01, 9.49111029e-01, 8.21431565e-01],
        [1.72489063e-01, 3.04929568e-01, 2.01062331e-01],
        [5.30773128e-01, 5.21972288e-02, 9.27587272e-01]],

       [[4.60077041e-01, 4.50125157e-01, 9.61917657e-01],
        [5.37518045e-01, 6.59826367e-01, 9.62296852e-01],
        [2.60588291e-01, 7.48873790e-01, 5.78263194e-01]],

       [[3.16899292e-01, 9.46897593e-01, 9.18974900e-04],
        [4.98248212e-01, 2.40172910e-02, 2.10639851e-01],
        [7.27027457e-01, 2.75122014e-01, 6.03604977e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [265]:
mat2d = rng.integers(100, size=(10, 10))
print(mat2d)
print(f"maximum: {mat2d.max()} minimum: {mat2d.min()}")

[[68 97 29 30 81 71 87 11 40  9]
 [28  1 70 94 45 87 49 84 53 15]
 [ 4 49  6 35 67 56 32 92 68 15]
 [87 70 97 48 79 48 39 73 60 12]
 [21 55 42 47 14 99 86 61 36 80]
 [32 18 12 19 66 54 40 36 37 62]
 [71 86  0 13 64 34 86 88 28 96]
 [69 75 34  4 13 60 74 91 80 16]
 [23 59 46 47 40 66 59  4  4 13]
 [24 95 45 78 90 24 26 39 55 38]]
maximum: 99 minimum: 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [266]:
vector = rng.random(30)
mean = np.mean(vector)
mean

0.49029233393766264

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [267]:
mat2d = np.ones((6, 6), dtype=np.int32)
mat2d[1:-1, 1: -1] = 0
mat2d

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [268]:
matrix3d = rng.integers(10, 100, size=(3,3))
bordered = np.pad(matrix3d, pad_width = 1, constant_values = 0)
bordered

array([[ 0,  0,  0,  0,  0],
       [ 0, 32, 88, 32,  0],
       [ 0, 20, 15, 42,  0],
       [ 0, 85, 28, 92,  0],
       [ 0,  0,  0,  0,  0]], dtype=int64)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [269]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [270]:
mat5x5 = np.diag(np.arange(1,5), k = -1)
mat5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [271]:
board = np.zeros((8,8), dtype = np.int32)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [272]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [273]:
def f(i, j):
    return (i + j) % 2
board = np.fromfunction(f, (8,8), dtype = np.int8)
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [274]:
mat = rng.integers(100, size=(5,5))
dfmax, dfmin = mat.max(), mat.min()
df = (mat - dfmin)/(dfmax - dfmin)
print(df)

[[0.53658537 0.14634146 0.7804878  0.53658537 0.45121951]
 [0.80487805 0.30487805 0.62195122 0.13414634 0.08536585]
 [0.75609756 0.79268293 0.06097561 0.82926829 1.        ]
 [0.52439024 0.13414634 0.97560976 0.54878049 0.12195122]
 [0.90243902 0.         0.68292683 0.95121951 0.64634146]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [275]:
rgbadt = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
image = np.array([(13, 45, 56, 255), (53, 65, 136, 255), (183, 25, 96, 255)], dtype = rgbadt)
image

array([( 13, 45,  56, 255), ( 53, 65, 136, 255), (183, 25,  96, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [276]:
mat5x3 = rng.integers(10, size=(5,3))
print(mat5x3)
mat3x2 = rng.integers(10, size=(3,2))
print(mat3x2)
product = np.matmul(mat5x3, mat3x2)
product

[[5 0 9]
 [6 3 8]
 [7 7 7]
 [3 5 2]
 [7 5 2]]
[[0 5]
 [4 5]
 [0 1]]


array([[ 0, 34],
       [12, 53],
       [28, 77],
       [20, 42],
       [20, 62]], dtype=int64)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [277]:
arr = np.arange(15)
arr[(arr > 3) & (arr < 8)] = -arr[(arr > 3) & (arr < 8)]
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [278]:
#print(sum(range(5),-1)) #9
#from numpy import *
#print(sum(range(5),-1))  #10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [279]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [280]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [281]:
def roundAwayFromZero(array):
    a = np.abs(array)
    b = np.floor(a) + np.floor(2*(a%1))
    return np.copysign(b, array)

x = np.linspace(-5, 5, 20)
roundAwayFromZero(x)

array([-5., -4., -4., -3., -3., -2., -2., -1., -1., -0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [282]:
np.intersect1d([1,2,3,4], [3,5,6,7])

array([3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [283]:
settings = np.seterr(all='ignore')
np.ones(1) / 0
#np.seterr(**settings)

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [284]:
np.sqrt(-1) == np.emath.sqrt(-1) #first'll return nan and second will return complex number

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [285]:
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-10-25 2022-10-26 2022-10-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [286]:
dates = np.arange(np.datetime64('2016-07'), np.datetime64('2016-08'), dtype = 'datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [287]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [288]:
x = rng.random(5, dtype=np.double)*10
print(x)
print(x.astype(np.int32))
print(np.trunc(x))
print(np.floor(x))
print(np.fix(x))

[2.55890796 0.2166779  5.92431688 7.47026648 7.406601  ]
[2 0 5 7 7]
[2. 0. 5. 7. 7.]
[2. 0. 5. 7. 7.]
[2. 0. 5. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [289]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [290]:
def generate_integers():
    for i in np.arange(10):
        yield i
np.fromiter(generate_integers(), dtype=np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [291]:
x = np.linspace(0, 1, num=12, endpoint=True)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [292]:
x = rng.random(10)
x.sort()
x

array([0.01602546, 0.04469532, 0.35162233, 0.3890442 , 0.49566854,
       0.5107374 , 0.6221203 , 0.65579147, 0.7806151 , 0.85254764])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [293]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [294]:
A = np.random.randint(0, 2, size=5)
B = np.random.randint(0, 2, size=5)
print(A, B)
#Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A, B)
print(equal)
#Checking both the shape and the element values, no tolerance (values have to be exact)
equal = np.array_equal(A,B)
print(equal)

[0 0 1 1 1] [0 1 0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [295]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1
print(Z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [296]:
Z = np.random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.03042744 0.43982715 0.86072575 0.71458223 0.28144117 0.69721616
 0.99970961 0.14745644 0.88822757 0.93048928]
[0.52943155 1.26135754 0.45862702 0.53417779 1.38208551 1.50522663
 1.56214143 0.05659544 1.24750155 1.47846633]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [297]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.28256194 0.8533934  0.32539968 0.84501174 0.67568186 0.78225401
 0.84733858 0.71487404 0.88900099 0.11527062]
[0.28256194 0.8533934  0.32539968 0.84501174 0.67568186 0.78225401
 0.84733858 0.71487404 0.         0.11527062]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [298]:
Z = np.zeros((5,5), [('x', np.float),('y', np.float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [299]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [300]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [301]:
np.set_printoptions(threshold=256)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [302]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
Z[index]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
20.68253125423546


21

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [303]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [304]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# import scipy
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print(D)

[[0.         0.40610235 1.01886103 0.27068012 1.00618905]
 [0.40610235 0.         0.90055075 0.46249409 0.91457266]
 [1.01886103 0.90055075 0.         0.77440093 0.06523375]
 [0.27068012 0.46249409 0.77440093 0.         0.75402626]
 [1.00618905 0.91457266 0.06523375 0.75402626 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [305]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [306]:
from io import StringIO


s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=-1)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [307]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [308]:
X, Y = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [309]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [310]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-0.03618946, -0.11030469,  0.01549118,  0.4175958 ,  0.42466236,
         0.06671693, -0.19061268, -0.35118135, -0.18799259, -0.04818551],
       [-0.26179903, -0.17671261,  0.29093429,  0.0079641 ,  0.4665224 ,
        -0.17617172,  0.08886552, -0.30336944, -0.41225768,  0.47602417],
       [-0.27902359, -0.27904999,  0.0809925 ,  0.38391494, -0.07673388,
         0.21964269,  0.36282044, -0.21150587,  0.04100469, -0.24206193],
       [-0.41785706,  0.23388101,  0.3738436 ,  0.42542117, -0.26229554,
         0.29479676, -0.04935673, -0.20565739, -0.38512697, -0.00764886],
       [ 0.35186734, -0.28357919,  0.0948531 , -0.11023925, -0.12418189,
        -0.1971277 , -0.18462275,  0.32923159, -0.12905653,  0.25285526]])

#### 59. How to sort an array by the nth column? (★★☆)

In [311]:
Z = np.random.randint(0,10,(4,4))
print(Z)
print(Z[Z[:,2].argsort()])

[[0 9 4 6]
 [8 1 5 9]
 [0 3 7 5]
 [0 8 9 7]]
[[0 9 4 6]
 [8 1 5 9]
 [0 3 7 5]
 [0 8 9 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [312]:
Z = np.random.randint(0,3,(3,10))
print(not (Z.any(axis=0).any()))

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [313]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = np.abs(Z - z).argmin()
print(Z[m])

0.5097349008088279


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [314]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [315]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [316]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[3. 2. 3. 2. 5. 3. 5. 2. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [317]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [318]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [319]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[73 53 59 63]
 [45 42 57 37]
 [70 50 63 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [320]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50536024 0.46759545 0.50998724 0.61940545 0.52727178 0.58854502
 0.47095051 0.37395162 0.45926762 0.67804646]


#### 69. How to get the diagonal of a dot product? (★★★)

In [321]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.50949614, 1.60025045, 1.05447608, 0.92244838, 1.56104898])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [322]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [323]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [324]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [325]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 93) ( 0, 96) ( 4, 13) ( 4, 32) ( 9, 14) ( 9, 40) (13, 32) (14, 40)
 (16, 19) (16, 35) (18, 19) (18, 38) (19, 35) (19, 38) (19, 71) (20, 34)
 (20, 59) (20, 80) (20, 88) (34, 80) (43, 67) (43, 98) (56, 86) (56, 93)
 (59, 88) (67, 98) (71, 71) (86, 93) (93, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [326]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [327]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [328]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [329]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.65676454, -0.0063937 , -0.72508614,  0.15365635, -0.01098583,
       -0.28558308, -0.58467179,  0.91560865, -0.36448816,  0.39346238,
       -0.47075779, -0.82355852,  0.48961164,  0.48174023,  0.14876333,
       -0.53339398,  0.92140022, -0.47660356,  0.71525134,  0.01366081,
       -0.34746692,  0.77856499, -0.95472195, -0.99676847, -0.3159507 ,
       -0.73414743,  0.10672621, -0.71046698,  0.6021725 , -0.29571633,
       -0.70578777, -0.60024816, -0.79703055, -0.39865149, -0.62835468,
        0.0863869 , -0.6415744 , -0.05602608,  0.25336516, -0.64678399,
       -0.70650905,  0.83078768,  0.3672334 ,  0.30600143, -0.09080654,
        0.93654272,  0.305748  ,  0.41343245, -0.40157237, -0.60606804,
        0.30328696,  0.05121902,  0.75669475,  0.6941603 , -0.13031858,
        0.68380583, -0.32653416,  0.64810272, -0.45949095, -0.54379472,
        0.87871397,  0.58505289,  0.75083167, -0.7842825 , -0.35473919,
       -0.73093662,  0.63681586, -0.86381865,  0.75423461,  0.80

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [330]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.6005142  10.66307809  0.34861762  8.41301953  6.41209799  0.38892889
  5.52153813  8.46025833  6.45294544  5.23290917]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [331]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.35150168  6.66105405  4.88856313  0.36416461 11.17805334  1.30457842
   8.07141357  0.49641084  3.16516165  0.99253   ]
 [ 2.19194514  1.75847339  4.22592415  0.45826861  6.36456426  0.68420644
   7.9427673   3.55234237  1.56481728  4.21887779]
 [ 9.6854412   3.80373355 12.79323984 10.48548115  6.24251771 13.42950928
  17.56185387  4.72171335 10.73986783 13.1370366 ]
 [ 7.13616706  4.28902127  4.94650284  8.31981875  6.83366507  6.26640552
   0.97076131 11.61651226  8.99466063  7.95267714]
 [ 6.13193397  0.23580164  4.35045914  8.34630345 10.77626381  7.85638126
   0.81389059  8.25148424 10.26349188  3.65968106]
 [10.68737937  3.63772079 12.99702983  9.48888639  1.67869127  9.50812106
  16.91673814  1.12906452  7.40807233  4.96816364]
 [11.12941184  6.71672171 13.1104082   9.10746457  4.93391556  7.91829954
  16.68026089  3.56057848  6.06220292  1.59755512]
 [ 3.0508743   3.69744935  4.91150053  0.87187973  7.9435604   0.37430378
   8.43741408  1.79544841  1.72108739  2.29434701]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [332]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 9 3 8 8 2 7 5 8 9]
 [5 1 6 7 8 3 1 5 5 1]
 [3 4 6 7 5 3 7 5 7 4]
 [9 6 2 6 5 4 6 6 6 7]
 [6 0 4 6 6 7 3 0 6 8]
 [9 4 5 5 9 0 0 1 6 9]
 [1 0 3 2 9 5 2 9 1 6]
 [3 4 0 9 4 2 0 4 5 3]
 [2 3 1 6 7 1 6 3 4 9]
 [0 9 4 0 8 4 0 0 4 0]]
[[0 0 0 0 0]
 [0 4 9 3 8]
 [0 5 1 6 7]
 [0 3 4 6 7]
 [0 9 6 2 6]]


C:\Users\Lenovo\anaconda3\envs\numpyPrjct\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [333]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [334]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [335]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [336]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 1]
   [1 4 0]
   [0 0 1]]

  [[2 1 3]
   [4 0 3]
   [0 1 4]]

  [[1 3 1]
   [0 3 0]
   [1 4 2]]

  ...

  [[1 0 0]
   [1 2 0]
   [4 4 3]]

  [[0 0 1]
   [2 0 4]
   [4 3 3]]

  [[0 1 2]
   [0 4 1]
   [3 3 0]]]


 [[[1 4 0]
   [0 0 1]
   [3 3 0]]

  [[4 0 3]
   [0 1 4]
   [3 0 1]]

  [[0 3 0]
   [1 4 2]
   [0 1 3]]

  ...

  [[1 2 0]
   [4 4 3]
   [2 2 2]]

  [[2 0 4]
   [4 3 3]
   [2 2 0]]

  [[0 4 1]
   [3 3 0]
   [2 0 4]]]


 [[[0 0 1]
   [3 3 0]
   [2 0 0]]

  [[0 1 4]
   [3 0 1]
   [0 0 4]]

  [[1 4 2]
   [0 1 3]
   [0 4 2]]

  ...

  [[4 4 3]
   [2 2 2]
   [2 0 0]]

  [[4 3 3]
   [2 2 0]
   [0 0 2]]

  [[3 3 0]
   [2 0 4]
   [0 2 4]]]


 ...


 [[[3 4 4]
   [0 0 0]
   [0 4 4]]

  [[4 4 4]
   [0 0 4]
   [4 4 1]]

  [[4 4 3]
   [0 4 4]
   [4 1 4]]

  ...

  [[3 2 1]
   [4 4 3]
   [2 4 1]]

  [[2 1 1]
   [4 3 2]
   [4 1 0]]

  [[1 1 0]
   [3 2 4]
   [1 0 3]]]


 [[[0 0 0]
   [0 4 4]
   [2 2 0]]

  [[0 0 4]
   [4 4 1]
   [2 0 1]]

  [[0 4 4]
   [4 1 4]
   [0 1 3]]

  ...

  [[4

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [337]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  4  8 15  8]
 [ 4  3  9 15  9]
 [ 8  9  2 42 12]
 [15 15 42  6 14]
 [ 8  9 12 14  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [338]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [339]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [340]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [341]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9995 9998 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [342]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [343]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [344]:
x = np.random.randint(5e4)

%timeit np.power(x,3)
%timeit x*x*x
#%timeit np.einsum('i,i,i->i',x,x,x)

922 ns ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
85.6 ns ± 1.04 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [345]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [346]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[1 2 1]
 [3 2 1]
 [1 1 2]
 [0 3 0]
 [2 4 4]
 [2 1 0]
 [4 1 3]
 [3 3 3]
 [0 3 2]
 [2 4 2]]
[[1 2 1]
 [3 2 1]
 [1 1 2]
 [0 3 0]
 [2 4 4]
 [2 1 0]
 [4 1 3]
 [0 3 2]
 [2 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [347]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [348]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [349]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.03998005, 0.06558174, 0.11665996, 0.07434045, 0.02943564,
        0.03197108, 0.04084073, 0.06657366, 0.02921761, 0.05257988],
       [0.27870421, 0.45717567, 0.81324608, 0.51823334, 0.20519822,
        0.22287303, 0.28470409, 0.46409044, 0.20367832, 0.36653864],
       [0.29962243, 0.49148911, 0.87428448, 0.55712948, 0.22059943,
        0.23960083, 0.30607263, 0.49892287, 0.21896545, 0.39404929],
       [0.28384206, 0.4656036 , 0.8282381 , 0.52778686, 0.208981  ,
        0.22698165, 0.28995255, 0.47264585, 0.20743309, 0.3732957 ],
       [0.10698906, 0.17550074, 0.31218917, 0.19893958, 0.07877156,
        0.08555657, 0.1092923 , 0.17815519, 0.0781881 , 0.14070697],
       [0.18829023, 0.30886406, 0.54942225, 0.35011411, 0.1386302 ,
        0.15057116, 0.1923437 , 0.31353562, 0.13760337, 0.24763044],
       [0.33115047, 0.54320649, 0.96628185, 0.61575392, 0.2438122 ,
        0.26481304, 0.3382794 , 0.55142248, 0.24200629, 0.43551348],
       [0.11366263, 0.1864478 , 0.3316623

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [350]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [351]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [352]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21170436  0.20285382]
